id: I67DAAD77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:11:29+00:00'
last_modified: '2022-06-08T16:39:42.187102+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19093
  title: ཚད་མ་རིགས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    471B:
      image_group_id: I2PD20732
      title: ''
      total_pages: 508
      order: 1
      base_file: 471B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
