id: P010666
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:58.253413
source_metadata:
  id: bdr:W2PD19093
  title: ཚད་མ་རིགས་རྒྱན།
  author: ''
  volumes:
    8fe8cb57c1f24bd6a01e847607bca852:
      image_group_id: I2PD20732
      title: ''
      volume_number: 1
      total_pages: 508
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
